arm:
  type: ur10
sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.68, -0.5, 1.24]
      rpy: ['pi/2', 1.175936, 0]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.68, 0.2, 1.24]
      rpy: ['pi/2', 1.175936, 0]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [-0.68, 1.0, 1.24]
      rpy: ['pi/2', 1.175936, 0]
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.68, -1.3, 1.24]
      rpy: ['pi/2', 1.175936, 0]
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [1.2, 2.5, 1.65]
      rpy: [0, 'pi/2', 0]
  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [0.3, 3.2, 1.48]
      rpy: [0, 'pi/2', 0]
  logical_camera_7:
    type: logical_camera
    pose:
      xyz: [0.3, -3.2, 1.48]
      rpy: [0, 'pi/2', 0]
  logical_camera_test:
    type: logical_camera
    pose:
      xyz: [0, 0, 0]
      rpy: ['pi/2', 'pi/2', 0]
  laser_scanner_1:
    type: laser_profiler
    pose:
      xyz: [1.2, 2.0, 1.6]
      rpy: ['pi/2', 'pi/2', 'pi']
